### ISSUE TITLE
Hackage documentation is garbled

### ISSUE THREAD

**Issue by FranklinChen** [ku-fpg/hood#2]
At http://hackage.haskell.org/package/hood-0.2.1/docs/src/Debug-Hood-Observe.html there are stray `\begin{code}` and `\end{code}` directives throughout.

**Comment by RyanGlScott** [comment]
Yeah, this is one of my biggest gripes with Literate Haskell in general. @andygill, would you be opposed to converting the source into a regular `.hs` file with comments?

**Comment by andygill** [comment]
I'd be just fine with converting it. Having someone look at using `Generic`, and clean up / modernize the API would be useful thing to do as well.

**Comment by RyanGlScott** [comment]
Cool. Once #1 is resolved, I'll try to fix this issue.

**Comment by FranklinChen** [comment]
I noticed this documentation glitch because I'm planning to write one of my "24 days of Hackage, 2015" posts on Hood and GHood. Do you want me to hold off on this one?

**Comment by andygill** [comment]
Can you give us until Monday to see what we can do to clean it up?

**Comment by FranklinChen** [comment]
Sure, I'm in no rush.

**Comment by RyanGlScott** [comment]
I just published a shiny new [`hood-0.3`](http://hackage.haskell.org/package/hood-0.3) to Hackage.

I can't wait to see the 24DoH post on it!
