### ISSUE TITLE
Home page link is wrong

### ISSUE THREAD

**Issue by FranklinChen** [ku-fpg/hood#3]
https://hackage.haskell.org/package/hood has a home page link that is wrong. I found the actual URL http://ku-fpg.github.io/software/hood/

**Comment by andygill** [comment]
I'll put a tmp URL link to make the old address work for now.

**Comment by andygill** [comment]
I've fixed the cabal file on hackage.

**Comment by RyanGlScott** [comment]
This seems to have been fixed, so closing.
