### ISSUE TITLE
Index out of range when the observed function throws an error 

### ISSUE THREAD

**Issue by igrep** [ku-fpg/hood#5]
# Problem

Index out of range error thrown by [`eventsToCDS`'s `array` function call](https://github.com/ku-fpg/hood/blob/fe4b04bae03fc059e2719cbb27f1b9b45e277590/Debug/Hood/Observe.hs#L696) when the observed function **pattern-matches on a value whose type is Generic-derived-Observable instance** throws an error.

# Minimum program to reproduce

```haskell
#!/usr/bin/env stack
{-# LANGUAGE DeriveGeneric #-}
-- stack --resolver lts-8.4 runghc --package hood

import           Debug.Hood.Observe
import           GHC.Generics


data Hoge =
  Hoge
    { hoge1 :: Int
    , hoge2 :: String
    } deriving Generic

instance Observable Hoge


main :: IO ()
main = runO $ print $ f undefined


f :: Hoge -> Bool
f = observe "f" f'
f' :: Hoge -> Bool
f' h@(Hoge _h1 _h2) = error "ERROR"
```

And here's the output:

```
[Escaping Exception in Code : Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries\base\GHC\Err.hs:79:14 in base:GHC.Err
  undefined, called at hood-error-case.hs:19:25 in main:Main]

hood-error-case.exe: Ix{Int}.index: Index (12) out of range ((0,11))
```

**Comment by igrep** [comment]
According to my debug code, the Index (12) out of range ((0,11)) error happens because one of the generated node ids is skipped (maybe by the exception) without getting counted as an event by `sendEvent`.

I'm going to investigate its more detailed cause and fix it.
Do you have any idea on the cause or the solution?

**Comment by andygill** [comment]
Thanks for finding this, and the test case. I think that we need to catch exceptions when we are ignoring them.
